title = "Software As Craft"
copyright = "Copyright © 2023 Software as Craft LLC."
paginate = 9
enableGitInfo = false
sectionPagesMenu = 'main'

# additional settings
baseURL = 'https://www.softwareascraft.com/'
canonifyURLs = false
enableEmoji = true
enableRobotsTXT = true
enableInlineShortcodes = true
summaryLength = 20

# toml-docs-start timeout
timeout = "180s"
# toml-docs-end timeout

# toml-docs-start language
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# toml-docs-end language

# toml-docs-end language
[taxonomies]
    tag = 'tags'

[privacy]
    [privacy.vimeo]
        disabled = false
        simple = true

    [privacy.twitter]
        disabled = false
        enableDNT = true
        simple = true

    [privacy.instagram]
        disabled = false
        simple = true

    [privacy.youtube]
        disabled = false
        privacyEnhanced = true

[sharing]
    enabled = true
    sort = "weight"
    reverse = false
    webshare = true

[[sharing.providers]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
    icon = "fab linkedin"
    weight = 10

[[sharing.providers]]
    name = "Twitter"
    url = "https://twitter.com/home?status={url}"
    icon = "fab x-twitter"
    weight = 20

[[sharing.providers]]
    name = "Facebook"
    url = "https://www.facebook.com/sharer.php?u={url}"
    icon = "fab facebook"
    weight = 30

[[sharing.providers]]
    name = "WhatsApp"
    url = "whatsapp://send?text={title}%20{url}"
    icon = "fab whatsapp"
    weight = 40

[[sharing.providers]]
    name = "email"
    url = "{url}"
    icon = "fas link"
    weight = 50
    clipboard = true

[[module.imports]]
    path = 'github.com/gethinode/hinode'

