title = "Software As Craft"
baseURL = 'https://www.softwareascraft.com/'
copyright = "Copyright © 2023 Software as Craft LLC."
paginate = 9
enableGitInfo = false
endorse = false

# additional settings
canonifyURLs = false
enableEmoji = true
enableRobotsTXT = true
enableInlineShortcodes = true
summaryLength = 20

# toml-docs-start timeout
timeout = "180s"
# toml-docs-end timeout

# toml-docs-start language
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# toml-docs-end language

# toml-docs-end language
[taxonomies]
    tag = 'tags'

[privacy]
    [privacy.vimeo]
        disabled = false
        simple = true

    [privacy.instagram]
        disabled = false
        simple = true

    [privacy.youtube]
        disabled = false
        privacyEnhanced = true

[sharing]
    enabled = true
    sort = "weight"
    reverse = false
    webshare = true

[[sharing.providers]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
    icon = "fab linkedin"
    weight = 10

[[sharing.providers]]
    name = "Facebook"
    url = "https://www.facebook.com/sharer.php?u={url}"
    icon = "fab facebook"
    weight = 30

[[sharing.providers]]
    name = "email"
    url = "{url}"
    icon = "fas link"
    weight = 50
    clipboard = true

[outputFormats]
    [outputFormats.XML]
        isPlainText = false
        mediaType = "application/xml"
        isHtml = false
        noUgly = true
        permalinkable = false
        name = "xml"

[module]
    [module.hugoVersion]
        extended = true
        min = "0.120.0"
        max = ""
    [[module.mounts]]
        source = "archetypes"
        target = "archetypes"
    [[module.mounts]]
        source = "assets"
        target = "assets"
    [[module.mounts]]
        source = "i18n"
        target = "i18n"
    [[module.mounts]]
        source = "layouts"
        target = "layouts"
    [[module.mounts]]
        source = "static"
        target = "static"
    [[module.mounts]]
        source = "static/fonts"
        target = "static/fonts"
    [[module.mounts]]
        source = "content/en/docs/latest"
        target = "content/docs/1.0"
        lang = 'en'
    [[module.mounts]]
        source = "content/en"
        target = "content"
        lang = 'en'
        excludeFiles = 'docs/latest/*'
    [[module.imports]]
        path = "github.com/gethinode/hinode"

