[main]
    separator = "-"
#    this will display the hinode link for the theme
    endorse = false

    footerBelowFold = true
    enableDarkMode = true
    enableLanguageSelectionStorage = false
    modes = ["light", "dark"]
    canonifyAssetsURLs = false
    loading = "lazy"
    breakpoint = "md"
    [main.internalLinks]
        validate = true
    [main.build]
        transpiler = "libsass"
    [main.externalLinks]
        cue = true
        tab = true

[modules]
    core = ["bootstrap", "flexsearch", "fontawesome"]
    optional = ["leaflet", "katex"]
    excludeSCSS = ["bootstrap"]
    disableTemplate = ["katex"]

[home]
    sections = ["posts", "talks", "workshops"]
    fullCover = false
    centerHeadline = false
    style = ""
    [home.feature]
        orientation = "horizontal"
        color = "secondary"
        width = 6
        align = "start"

[sections]
    [sections.posts]
        title = "Posts"
        sort = "date"
        reverse = true
        cols = 4
        color = ""
        padding = "0"
        header = "full"
        footer = "none"
        orientation = "stacked"
        style = "border-0 card-zoom"
        homepage = 8
        separator = false
    [sections.talks]
        title = "Talks I Give"
        sort = "date"
        reverse = true
        cols = 4
        color = ""
        padding = "0"
        header = "full"
        footer = "none"
        orientation = "stacked"
        style = "border-0 card-zoom"
        homepage = 8
        separator = false
    [sections.workshops]
        title = "Workshops Available"
        sort = "date"
        reverse = true
        cols = 4
        color = ""
        padding = "0"
        header = "full"
        footer = "none"
        orientation = "stacked"
        style = "border-0 card-zoom"
        homepage = 8
        separator = false

# toml-docs-start navigation
[navigation]
    anchor = true
    logo = "/img/anvil.png"
    color = "body"
    fixed = true
    horizontal = false
    offset = "5.5rem"
    search = true
    searchModal = false
    breadcrumb = true
    toc = true
    sidebar = true
    size = "md"
# toml-docs-end navigation


[favicon]
    logo = "/img/anvil.png"
    sizes = [16, 32, 48]


# toml-docs-start managed-links
[links]
    aonw = "https://www.agileopennorthwest.org/"
    calendly = "https://calendly.com/paige-watson"
    fast-io ="https://fastagile.io"
    fast-guide = "https://www.fastagile.io/fast-guide"
    llewelyn-falco-li = "https://www.linkedin.com/in/llewellynfalco"
    llewelyn-falco-github = "https://github.com/isidore"
    mob-sh = "https://mob.sh"
    myturnyet-github = "https://github.com/MyTurnyet"
    myturn-yet-talks = "/talks"
    remote-mob-programming = "https://remotemobprogramming.org"
# toml-docs-end managed-links