[main]
    separator = "-"
    enableDarkMode = true

#    this will display the hinode link for the theme
    endorse = false

    footerBelowFold = true
 #   loading = "lazy"
 #   breakpoint = "md"
    [main.externalLinks]
        cue = true
        tab = true

[home]
    sections = ["posts"]
#    sections = ["posts", "talks", "workshops"]
    fullCover = false
    centerHeadline = false
    style = ""
    [home.feature]
        orientation = "horizontal"
        color = "secondary"
        width = 6
        align = "start"

# toml-docs-start navigation
[navigation]
    anchor = true
    logo = "/img/anvil.png"
    color = "body"
    fixed = true
    horizontal = false
    offset = "5.5rem"
    search = true
    searchModal = false
    breadcrumb = true
    toc = true
    sidebar = true
    size = "md"
# toml-docs-end navigation


[favicon]
    logo = "/img/anvil.png"
    sizes = [16, 32, 48]


# toml-docs-start managed-links
[links]
    calendly = "https://calendly.com/paige-watson"
    fast-io ="https://fastagile.io"
    fast-guide = "https://www.fastagile.io/fast-guide"
    llewelyn-falco-li = "https://www.linkedin.com/in/llewellynfalco"
    llewelyn-falco-github = "https://github.com/isidore"
    mob-sh = "https://mob.sh"
    myturnyet-github = "https://github.com/MyTurnyet"
    myturn-yet-talks = ""
    remote-mob-programming = "https://remotemobprogramming.org"
# toml-docs-end managed-links