[main]
    separator = "-"
#    this will display the hinode link for the theme
    endorse = false

    footerBelowFold = true
    enableDarkMode = true
    enableLanguageSelectionStorage = false
    modes = ["light", "dark"]
    canonifyAssetsURLs = false
    loading = "lazy"
    breakpoint = "md"
    [main.internalLinks]
        validate = true
    [main.build]
        transpiler = "libsass"
    [main.externalLinks]
        cue = true
        tab = true


[home]
    sections = ["posts", "talks", "workshops"]
    fullCover = false
    centerHeadline = false
    style = ""
    [home.feature]
        orientation = "horizontal"
        color = "primary"
        width = 6
        align = "start"
[posts]
    fullCover = true
    centerHeadline = false
    style = ""


[sections]
    [sections.posts]
        title = "Applying our craft..."
        buttonType = "link"
        sort = "date"
        reverse = true
        cols = 4
        color = ""
        padding = "2"
        header = "publication"
        footer = "tags"
        orientation = "stacked"
        style = "border-1 card-zoom"
        homepage = 8
    [sections.talks]
        title = "Talks I give..."
        sort = "date"
        reverse = true
        cols = 4
        color = ""
        padding = "2"
        header = "full"
        footer = "none"
        orientation = "stacked"
        style = "border-1 card-zoom"
        homepage = 8
        separator = false
    [sections.workshops]
        title = "Workshops available..."
        sort = "date"
        reverse = true
        cols = 4
        color = ""
        padding = "2"
        header = "full"
        footer = "none"
        orientation = "stacked"
        style = "border-1 card-zoom"
        homepage = 8
        separator = false

# toml-docs-start navigation
[navigation]
    anchor = true
    logo = "/img/anvil.png"
    color = "body"
    fixed = true
    horizontal = false
    offset = "5.5rem"
    search = true
    searchModal = false
    breadcrumb = true
    toc = true
    sidebar = true
    size = "md"
# toml-docs-end navigation


[favicon]
    logo = "/img/anvil.png"
    sizes = [16, 32, 48]


# toml-docs-start managed-links
[links]
    aonw = "https://www.agileopennorthwest.org/"
    book-peak = "https://en.wikipedia.org/wiki/Peak:_Secrets_from_the_New_Science_of_Expertise"
    book-thinking-fast-and-slow = "https://en.wikipedia.org/wiki/Thinking,_Fast_and_Slow"
    book-drive = "https://en.wikipedia.org/wiki/Drive:_The_Surprising_Truth_About_What_Motivates_Us"
    calendly = "https://calendly.com/paige-watson"
    fast-io ="https://fastagile.io"
    fast-guide = "https://www.fastagile.io/fast-guide"
    kuo-discovery-trees = "https://www.katanation.com/single-post/working-with-discovery-trees-by-steve-kuo"
    llewelyn-falco-li = "https://www.linkedin.com/in/llewellynfalco"
    llewelyn-falco-github = "https://github.com/isidore"
    mob-sh = "https://mob.sh"
    myturnyet-github = "https://github.com/MyTurnyet"
    myturn-yet-talks = "/talks"
    ottinger-scatter-gather = "https://www.industriallogic.com/blog/scatter-gather/"
    pomodoro-technique = "https://en.wikipedia.org/wiki/Pomodoro_Technique"
    remote-mob-programming = "https://remotemobprogramming.org"
    tdd-wikipedia = "https://en.wikipedia.org/wiki/Test-driven_development"

# toml-docs-end managed-links

[style]
    primary = "#2B6CB0"
    secondary = "#4A5568"
    success = "#38A169"
    info = "#3182CE"
    warning = "#ED8936"
    danger = "#E53E3E"
    light = "#F7FAFC"
    dark = "#1A202C"


[[params.plugins.css]]
    link = "plugins/font-awesome/v6/brands.css"
    lazy = true

[sharing]
enabled = true
sort = "weight"
reverse = false
webshare = true

[[sharing.providers]]
    name = "Bluesky"
    url = "https://bsky.app/intent/compose?text=Check%20out%20this%20great%20blog%20post%20by%20%40softwareascraft.com%3A%0A{title}%3A%0A{url}"
    icon = "fab bluesky"
    weight = 10
    target = "_blank"

[[sharing.providers]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
    icon = "fab linkedin"
    weight = 20
    target = "_blank"

[[sharing.providers]]
    name = "Facebook"
    url = "https://www.facebook.com/sharer.php?u={url}"
    icon = "fab facebook"
    weight = 30
    target = "_blank"

[[sharing.providers]]
    name = "email"
    url = "{url}"
    icon = "fas link"
    weight = 50
    clipboard = true
    target = "_blank"

[analytics]
    [analytics.goatcounter]
        name = "softwareascraft"
        enable = true