[context.production.environment]
    HUGO_VERSION = "0.120.4"
    HUGO_ENV = "production"

[context.deploy-preview.environment]
    HUGO_VERSION = "0.120.4"

[build]
    publish = "public"
    command = "hugo --minify --buildFuture"
[build.environment]
    HUGO_ENV = "production"
    HUGO_VERSION = "0.120.4"
