[[main]]
  name = "Home"
  pageRef = "/"
  weight = 5

[[main]]
  name = "Posts"
  pageRef = "/posts"
  weight = 10

[[main]]
  name = "Developing with ADHD"
  pageRef = "/adhd"
  weight = 20


[[main]]
  name = "Talks"
  pageRef = "/talks"
  weight = 30


[[main]]
  name = "Workshops"
  pageRef = "/workshops"
  weight = 40

[[main]]
  name = "About Me"
  pageRef = "/about"
  weight = 45

[[social]]
  name = "LinkedIn"
  pre = "fab linkedin"
  url = "https://www.linkedin.com/in/paige-is-xp/"
  weight = 10

[[social]]
  name = "BlueSky"
  pre = "fab bluesky"
  url = "https://bsky.app/profile/softwareascraft.com"
  weight = 15

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/MyTurnyet"
  weight = 20

[[social]]
  name = "Mastodon"
  pre = "fab mastodon"
  url = "https://techhub.social/@paigewatson"
  weight = 30

[[social]]
name = "Calendar"
pre = "fa calendar-plus"
url = "https://calendly.com/paige-watson"
weight = 50
